### ISSUE TITLE
How to generate optical flow

### ISSUE THREAD

**Issue by liyunsheng13** [wangbo-zhao/2022CVPR-MMMMTBVS#1]
Hi

Congratulations to the good work. I'm curious how you use RAFT to generate optical flow. Do you save the raw data or convert it to an image and then save? Moreover, since features of optical flow is not aligned with the features of the video in terms of the length of frames, how do you align this gap?

Thanks

**Comment by wangbo-zhao** [comment]
Thanks. First, we need to convert the raw data into a series of images. Then, we can adopt the RAFT to generate the flow map from frame t to frame t+1.

What do you mean about the second problem?

**Comment by liyunsheng13** [comment]
For my first question, I mean how you save the flow map. Do you save it into an image or the raw tensor. I'm curious about the influence of the precision of the flow. Second, I mean if the video has length 't' but the flow map given by the video should be 't-1'. But after reading your paper, it looks like the flow map also has length 't'. How did you do that?

**Comment by wangbo-zhao** [comment]
The raw tensor from RAFT is [H, W, 2], and we can convert it into RGB
format [H, W, 3], then we can save it.      For the second problem, there
are only a few annotated frames in A2D and JHMDB, so we only need to
generate optical flow maps for these frames instead of all frames.

Yunsheng Li ***@***.***> 于2022年4月22日周五 09:24写道：
